# 菜单
menu:
  home: / || fa fa-home
  tags: /tags/ || fa fa-tags

sidebar:
  # Sidebar Position.
  position: left

  # Sidebar Display (only for Muse | Mist), available values:
  #  - post    expand on posts automatically. Default.
  #  - always  expand for all pages automatically.
  #  - hide    expand only when click on the sidebar toggle icon.
  #  - remove  totally remove sidebar including sidebar toggle.
  display: always

  # Sidebar padding in pixels.
  padding: 18
  # Sidebar offset from top menubar in pixels (only for Pisces | Gemini).
  offset: 12

# hexo-word-counter
post_meta:
  item_text: true # 是否显示文字

symbols_count_time:
  separated_meta: true # 是否另起一行
  item_text_total: false # 页面底部统计数量前是否显示文字描述

# hexo-generator-searchdb
local_search:
  enable: true
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1

# leancloud_counter_security
leancloud_visitors:
  enable: true
  app_id: 3EC6DlIt15eVYStwSVsDsQ2P-MdYXbMMI
  app_key: KKBQicvLunsmAfgH3DJJXvng
  security: false
